language: node_js
node_js:
- '0.10'
# uncomment these services for back-end REST API apps
services:
 - mongodb
#  - redis-server
before_install:
# - npm install grunt-cli
# - npm install bower
install:
- npm install
- bower install
